---
- hosts: gluster-cluster
  gather_facts: false

  roles:
      - basic-stuff
      - mirrorlist
      - gluster-cluster

- hosts: client.example.lan
  roles:
      - basic-stuff
      - gluster-client
